#LifeCore plugin configuration file

website-url: https://azisaba.net/

wiki-url: https://azisabaofficial.playing.wiki/

unofficial-wiki-url: https://aziserver.playing.wiki/

guide: written_book{pages:['["",{"text":" \\u0020 \\u0020 life","color":"red"},{"text":"\\u3078\\u3088\\u3046\\u3053\\u305d\\uff01\\uff01\\n\\n","color":"reset"},{"text":"\\u516c\\u5f0f\\u30a6\\u30a3\\u30ad","bold":true},{"text":"\\u306f","color":"reset"},{"text":"\\u201d\\u3053\\u3053\\u201d","bold":true,"color":"blue","clickEvent":{"action":"open_url","value":"https://azisabaofficial.playing.wiki/d/Life%c0%b8%b3%e8%bb%aa"}},{"text":"\\u3092\\u30af\\u30ea\\u30c3\\u30af\\uff01\\n\\n \\u0020 \\u0020 \\u0020 \\u0020","color":"reset"},{"text":"\\uff5e","bold":true},{"text":"\\u76ee\\u6b21","bold":true,"color":"dark_blue"},{"text":"\\uff5e","color":"reset","bold":true},{"text":"\\n\\n- ","color":"reset"},{"text":"\\u5404","underlined":true},{"text":"\\u30ef\\u30fc\\u30eb\\u30c9","underlined":true,"color":"dark_red"},{"text":"\\u8aac\\u660e","color":"reset","underlined":true},{"text":" \\uff12\\u223c\\uff13\\n- ","color":"reset"},{"text":"\\u7d4c\\u6e08\\u30b7\\u30b9\\u30c6\\u30e0","bold":true,"underlined":true,"color":"gold"},{"text":"\\u306b\\u3064\\u3044\\u3066","color":"reset","underlined":true},{"text":" \\uff14\\n- ","color":"reset"},{"text":"\\u3088\\u304f\\u4f7f\\u3046\\u30b3\\u30de\\u30f3\\u30c9\\u7b49","underlined":true,"color":"dark_aqua"},{"text":" \\uff15\\u223c\\uff17\\n- ","color":"reset"},{"text":"\\u56f0\\u3063\\u305f\\u3068\\u304d\\u306f\\uff1f","bold":true,"underlined":true,"color":"gray"},{"text":" \\uff18","color":"reset"}]','["",{"text":" \\u0020 \\u0020\\uff5e\\u5404\\u30ef\\u30fc\\u30eb\\u30c9\\u8aac\\u660e\\uff5e","bold":true},{"text":"\\n\\nlife\\u306b\\u306f,","color":"reset"},{"text":"\\u30e1\\u30a4\\u30f3\\u5efa\\u7bc9\\u30ef\\u30fc\\u30eb\\u30c9","bold":true,"color":"dark_green"},{"text":"\\u3068\\n","color":"reset"},{"text":"\\u8cc7\\u6e90\\u30ef\\u30fc\\u30eb\\u30c9","bold":true,"color":"gold"},{"text":"\\uff13\\u7a2e","color":"reset","underlined":true},{"text":"\\u304c\\u3042\\u308a\\u307e\\u3059\\u3002\\n\\n","color":"reset"},{"text":"\\uff5e\\u30e1\\u30a4\\u30f3\\u5efa\\u7bc9\\u30ef\\u30fc\\u30eb\\u30c9\\u306b\\u3064\\u3044\\u3066\\uff5e","bold":true},{"text":"\\n\\n","color":"reset"},{"text":"\\u30e1\\u30a4\\u30f3\\u5efa\\u7bc9\\u30ef\\u30fc\\u30eb\\u30c9","bold":true,"color":"dark_green"},{"text":"\\u306f,\\n\\n- ","color":"reset"},{"text":"\\u8cc7\\u6e90\\u76ee\\u7684\\u306e\\n","bold":true,"underlined":true,"color":"red"},{"text":"\\u0020\\u0020","color":reset"},{"text":"\\u5730\\u5f62\\u7834\\u58ca\\u7981\\u6b62","bold":true,"underlined":true,"color":"red"}]','["",{"text":"- "},{"text":"\\u30ef\\u30fc\\u30eb\\u30c9\\u30ea\\u30bb\\u30c3\\u30c8","underlined":true,"color":"dark_aqua"},{"text":"\\u306a\\u3057","color":"reset","underlined":true},{"text":"\\n\\n\\u30fb\\u30ef\\u30fc\\u30eb\\u30c9\\u30ea\\u30bb\\u30c3\\u30c8\\u304c\\u7121\\u3044\\n \\u306e\\u3067,\\n ","color":"reset"},{"text":"\\u4fdd\\u8b77\\u3084\\u5efa\\u7bc9\\u306f\\u6d88\\u3048\\u307e\\u305b\\u3093\\u3002","underlined":true},{"text":"\\n\\n- ","color":"reset"},{"text":"\\u571f\\u5730\\u306e","underlined":true},{"text":"\\u4fdd\\u8b77","bold":true,"underlined":true,"color":"dark_green"},{"text":",","color":"reset","underlined":true},{"text":"\\u5efa\\u7bc9","bold":true,"underlined":true,"color":"light_purple"},{"text":"\\n \\u0020","color":"light_purple"},{"text":"\\u304c\\u3067\\u304d\\u307e\\u3059\\u3002\\n\\n\\u30fb\\u5bb6\\u306a\\u3069\\u306e\\u5efa\\u7bc9\\u306f,\\n ","color":"reset"},{"text":"\\u5efa\\u7bc9\\u30ef\\u30fc\\u30eb\\u30c9","bold":true,"color":"dark_green"},{"text":"\\u306e\\n ","color":"reset"},{"text":"\\u904b\\u55b6\\u8857","color":"gold"},{"text":"\\u306e","color":"reset"},{"text":"\\u5916","bold":true,"underlined":true,"color":"red"},{"text":"\\u306b\\n ","color":"reset"},{"text":"\\u753a","bold":true},{"text":"\\u3092\\u4f5c\\u3063\\u3066","color":"reset","underlined":true},{"text":"\\u5efa\\u7bc9\\u3057\\u3088\\u3046\\u3002\\n\\n ","color":"reset"}]','["",{"text":" \\u0020\\uff5e\\u7d4c\\u6e08\\u30b7\\u30b9\\u30c6\\u30e0\\u306b\\u3064\\u3044\\u3066\\uff5e","bold":true},{"text":"\\n\\n- ","color":"reset"},{"text":"\\u666e\\u901a\\u306e","underlined":true},{"text":"\\u304a\\u91d1","underlined":true,"color":"gold"},{"text":"\\u3082","color":"reset","underlined":true},{"text":"\\n \\u0020","color":"reset"},{"text":"\\u5b58\\u5728\\u3057\\u307e\\u3059\\u3002","underlined":true},{"text":"\\n \\u0020\\u4e3b\\u306b,\\n \\u0020","color":"reset"},{"text":"\\u30d7\\u30ec\\u30a4\\u30e4\\u30fc\\u9593\\u306e\\u53d6\\u5f15","underlined":true,"color":"dark_green"},{"text":"\\n \\u0020\\u3067\\u4f7f\\u308f\\u308c\\u308b\\u3082\\u306e\\u3067\\u3059\\u3002\\n\\n- ","color":"reset"},{"text":"\\u30a2\\u30a4\\u30c6\\u30e0\\u8ca9\\u58f2,\\u9001\\u91d1","bold":true,"color":"gold"},{"text":"\\u3084\\n \\u0020","color":"reset"},{"text":"\\u30aa\\u30fc\\u30af\\u30b7\\u30e7\\u30f3","bold":true,"color":"dark_blue"},{"text":"\\u3092\\n \\u0020\\u884c\\u3046\\u3053\\u3068\\u304c\\u3067\\u304d\\u307e\\u3059\\u3002","color":"reset"}]','["",{"text":" \\u0020 \\u0020== Home\\u95a2\\u9023 ==","bold":true},{"text":"\\n\\n","color":"reset"},{"text":"\\u30fb/home [\\u8a2d\\u5b9a\\u540d]\\n","bold":true},{"text":"-","bold":true,"color":"gold"},{"text":" \\u8a2d\\u5b9a\\u3055\\u308c\\u305fHome\\u306bTP\\u3057\\u307e\\u3059","color":"reset","bold":true},{"text":"\\n\\n","color":"reset"},{"text":"\\u30fb/spawn [\\u8a2d\\u5b9a\\u540d]\\n","bold":true},{"text":"-","bold":true,"color":"gold"},{"text":" Life\\u30b5\\u30fc\\u30d0\\u30fc\\u30ed\\u30d3\\u30fc\\u306b\\n \\u0020TP\\u3057\\u307e\\u3059","color":"reset","bold":true},{"text":"\\n\\n","color":"reset"},{"text":"\\u30fb/sethome [\\u8a2d\\u5b9a\\u540d]\\n","bold":true},{"text":"-","bold":true,"color":"gold"},{"text":" \\u4eca\\u7acb\\u3063\\u3066\\u3044\\u308b\\u5834\\u6240\\u306b\\u30db\\u30fc\\u30e0\\u3092\\n \\u0020\\u8aac\\u5b9a\\u3057\\u307e\\u3059","color":"reset","bold":true}]','["",{"text":"\\u30fb/delhome [\\u8a2d\\u5b9a\\u540d]\\n","bold":true},{"text":"-","bold":true,"color":"gold"},{"text":" \\u8a2d\\u5b9a\\u3055\\u308c\\u305fHome\\u3092\\u524a\\u9664\\u3057\\u307e\\u3059","color":"reset","bold":true}]','["",{"text":" \\u0020 ==\\u30c1\\u30a7\\u30b9\\u30c8\\u4fdd\\u8b77\\u95a2\\u9023==","bold":true},{"text":"\\n\\n\\u30fb","color":"reset"},{"text":"/lock [\\u884c\\u6570] [\\u6587\\u5b57\\u5217]\\n","bold":true},{"text":"-","bold":true,"color":"gold"},{"text":" \\u53f3\\u30af\\u30ea\\u30c3\\u30af\\u3067\\u9078\\u629e\\u3057\\u305f\\n \\u0020\\u4fdd\\u8b77\\u770b\\u677f\\u306e\\u6307\\u5b9a\\u3057\\u305f\\u884c\\u6570\\u3092\\n \\u0020\\u66f8\\u304d\\u63db\\u3048\\u308b","color":"reset","bold":true}]','["",{"text":" \\u0020 \\u0020 \\uff5e\\u56f0\\u3063\\u305f\\u3068\\u304d\\u306f\\uff1f\\uff5e","bold":true},{"text":"\\n\\n\\u30fb\\u3053\\u3053\\u3084","color":"reset"},{"text":"{\\u516c\\u5f0f\\u30a6\\u30a3\\u30ad}","bold":true,"color":"blue","clickEvent":{"action":"open_url","value":"https://azisabaofficial.playing.wiki/d/Life%c0%b8%b3%e8%bb%aa"}},{"text":"\\n ","bold":true,"color":"blue"},{"text":"\\u304b\\u3089\\u60c5\\u5831\\u3092\\u63a2\\u3063\\u3066\\u307f\\u3088\\u3046!\\n\\n\\u30fb\\u305d\\u308c\\u3067\\u3082\\n \\u5206\\u304b\\u3089\\u306a\\u3044\\u5834\\u5408\\u306f\\n","color":"reset"},{"text":" \\u9bd6\\u6c11\\u3084\\u904b\\u55b6","bold":true,"color":"dark_green"},{"text":"\\u306b\\u805e\\u3044\\u3066\\u307f\\u308b","color":"reset","bold":true},{"text":"\\n","color":"reset"},{"text":" \\u306e\\u3082\\u3088\\u3044\\u3067\\u3057\\u3087\\u3046\\uff01\\n\\n\\u30fb"},{"text":"\\u753a\\u306e\\u8aac\\u660e\\u306f","bold":true},{"text":"\\u3053\\u3053","bold":true,"underlined":true,"color":"blue","clickEvent":{"action":"open_url","value":"https://azisabaofficial.playing.wiki/d/Towny%a4%cb%a4%c4%a4%a4%a4%c6"}},{"text":"\\u3092\\n \\u898b\\u307e\\u3057\\u3087\\u3046\\u3002","color":"reset","bold":true}]'],title:"ガイドブック",author:"life鯖"}

guide-yarukoto: written_book{pages:['["",{"text":"Life\\u9bd6\\u306e\\u57fa\\u672c\\u306b\\u3064\\u3044\\u3066\\n"},{"text":"---------------","bold":true},{"text":"\\n\\n\\u9bd6\\u306b\\u30ed\\u30b0\\u30a4\\u30f3\\u3057\\u305f\\u3089\\n\\u307e\\u305a\\u306f","color":"reset"},{"text":"\\u753a","bold":true,"underlined":true},{"text":"\\u306b\\u6240\\u5c5e","color":"reset","underlined":true},{"text":"\\u3057\\u307e\\u3057\\u3087\\u3046\\n\\n","color":"reset"},{"text":"\\u203b\\u30b3\\u30de\\u30f3\\u30c9\\u306a\\u3069\\u306f","bold":true,"underlined":true,"color":"red"},{"text":"\\n ","color":"reset"},{"text":"/help town\\u3067","bold":true,"underlined":true,"color":"red"},{"text":"\\n ","color":"reset"},{"text":"\\u78ba\\u8a8d\\u3057\\u307e\\u3057\\u3087\\u3046","bold":true,"underlined":true,"color":"red"}]','["",{"text":"\\u753a\\u306b\\u5165\\u308c\\u3066\\u3082\\u3089\\u3063\\u305f\\u3089\\n\\u6b21\\u306f"},{"text":"\\u8cc7\\u6e90\\u30ef\\u30fc\\u30eb\\u30c9","bold":true,"color":"gold"},{"text":"\\n\\u306b\\u884c\\u3063\\u3066","color":"reset"},{"text":"\\u8cc7\\u6e90","bold":true,"underlined":true},{"text":"\\u3092\\u96c6\\u3081\\u307e\\u3057\\u3087\\u3046","color":"reset","underlined":true},{"text":"\\n\\n","color":"reset"},{"text":"\\u62e0\\u70b9\\u306e\\u5efa\\u7bc9\\u306b\\u5fc5\\u8981\\u306a\\n\\u8cc7\\u6e90\\u304c\\u305d\\u308d\\u3044,\\u753a\\u306b\\u6240\\u5c5e\\n\\u51fa\\u6765\\u305f\\u3089\\u62e0\\u70b9\\u3092\\n\\u5efa\\u3066\\u307e\\u3057\\u3087\\u3046","underlined":true}]','["",{"text":"\\u3053\\u3053\\u307e\\u3067\\u304f\\u308c\\u3070\\u3042\\u306a\\u305f\\u306f\\n\\u7acb\\u6d3e\\u306aLife\\u9bd6\\u6c11\\u3067\\u3059!","bold":true,"underlined":true},{"text":"\\n\\n\\u3053\\u308c\\u4ee5\\u964d\\u306f\\n","color":"reset"},{"text":"\\u521d\\u7d1a\\u30c0\\u30f3\\u30b8\\u30e7\\u30f3\\u306b\\u6311\\u3080,\\n\\u30e9\\u30f3\\u30af2\\u3092\\u76ee\\u6307\\u3059,\\n\\u304a\\u91d1\\u3092\\u96c6\\u3081\\u308b,\\n\\u62e0\\u70b9\\u3068\\u753a\\u3092\\u767a\\u5c55\\u3055\\u305b\\u308b\\u306a\\u3069","underlined":true}]','["",{"text":"\\u81ea\\u5206\\u304c\\n\\u3084\\u308a\\u305f\\u3044\\u3053\\u3068","bold":true,"underlined":true},{"text":"\\u3092\\u3084\\u308a\\u307e\\u3057\\u3087\\u3046","color":"reset","underlined":true},{"text":"\\n\\n\\u308f\\u304b\\u3089\\u306a\\u3044\\u3053\\u3068\\u304c\\u3042\\u308c\\u3070\\n","color":"reset"},{"text":"Wiki","bold":true,"color":"blue","clickEvent":{"action":"open_url","value":"https://azisabaofficial.playing.wiki/"}},{"text":"\\u3092\\u898b\\u307e\\u3057\\u3087\\u3046\\n\\n","color":"reset"},{"text":"\\u305d\\u308c\\u3067\\u306fLife\\u9bd6\\u3067\\u306e\\u751f\\u6d3b\\n\\u200b\\u3092\\u697d\\u3057\\u3093\\u3067\\u304f\\u3060\\u3055\\u3044\\uff01","underlined":true}]'],title:"アジ鯖に来たらやること",author:"life鯖"}

tutorial-teleport: e:tutorial:-42.5,20,252:0:0

pve-teleport: e:pve:2.5,33.0,197.5:0.0:-180.0

Rank:
  Rank1:
    - ''
    - '&bランクからアンロックされる機能'
    - '&3・/spawn'
    - '&3・水バケツ'
    - '&3・/sethome, /home'
    - '&3・ホーム最大個数：1'
  Rank2:
    - ''
    - '&bランク2からアンロックされる機能'
    - '&3・ホーム最大個数：2'
  Rank3:
    - ''
    - '&bランク3からアンロックされる機能'
    - '&3・ホーム最大個数：3'
  Rank4:
    - ''
    - '&bランク4からアンロックされる機能'
    - '&3・マグマバケツ'
    - '&3・MyPetで豚とゾンビをテイム可能'
    - '&3・ホーム最大個数：4'
  Rank5:
    - ''
    - '&bランク5からアンロックされる機能'
    - '&3・特殊エンチャント'
    - '&3・最大特殊エンチャント数1'
    - '&3・ホーム最大個数：5'
  Rank6:
    - ''
    - '&bランク6からアンロックされる機能'
    - '&3・MyPetで全モブテイム可能'
    - '&3・最大特殊エンチャント数3'
    - '&3・ホーム最大個数：6'
  Rank7:
    - ''
    - '&bランク7からアンロックされる機能'
    - '&3・最大特殊エンチャント数5'
    - '&3・ホーム最大個数：7'
  Rank8:
    - ''
    - '&bランク8からアンロックされる機能'
    - '&3・最大特殊エンチャント数7'
    - '&3・ホーム最大個数：8'
  Rank9:
    - ''
    - '&bランク9からアンロックされる機能'
    - '&3・最大特殊エンチャント数9'
    - '&3・ホーム最大個数：9'
  Rank10:
    - ''
    - '&bランク10からアンロックされる機能'
    - '&3・最大特殊エンチャント数11'
    - '&3・ホーム最大個数：10'

Help:
  Menu:
    - ''
    - '&b&lヘルプメニュー'
    - '&7-----------------------------'
    - '&3ガイドブックの入手 &a/guide'
    - '&3公式Wikiリンクの入手 &a/wiki'
    - '&3非公式Wikiリンクの入手 &a/wiki unofficial'
    - '&3ホームページリンクの入手 &a/web'
    - '&3町について &a/help town'
    - '&3お金について &a/help money'
    - '&3ランクについて &a/help rank'
    - '&3ダンジョンについて &a/help dungeon'
    - '&3よく使うコマンドについて &a/help command'
    - '&3ペットについて &a/help pet'
    - '&3MCMMOについて &a/help mcmmo'
    - '&3追加レシピについて &a/help recipe'
    - '&3追加エンチャントについて &a/help enchant'
    - '&3投票について &a/help vote'
    - '&3Life鯖の基本について &a/help basics'

  Town:
    - ''
    - '&b&l町について'
    - '&7-----------------------------'
    - '&3・町の作成 &a/town new 希望の村の名前'
    - '&3・町の銀行への入金。&a /town deposit 希望の金額'
    - '&3  土地の購入と維持費は町の銀行から引かれます'
    - '&3・町の拡張。町に隣接しているチャンクで &a/t claim'
    - '&3・町にユーザーを招待する &a/town add ユーザーネーム'
    - '&3・町への招待を受け取る &a/accept'
    - '&3・町への招待を拒否する &a/deny'
    - '&3・町のプロットを販売する &a/plot fs 値段'
    - '&3  初心者相手には無料で売ってあげましょう'
    - '&3・町のプロットを購入する &a/plot claim'
    - '&3・詳しくは町についてのWikiページを見てね'
    - '&fhttps://azisabaofficial.playing.wiki/d/Towny%a4%cb%a4%c4%a4%a4%a4%c6'

  Money:
    - ''
    - '&b&lお金について'
    - '&7-----------------------------'
    - '&3・所持金の確認 &a/money'
    - '&3・運営ショップでものを買う &a/shop'
    - '&3・運営ショップでものを売る(出てくるチェストにアイテムを入れる) &a/sell'
    - '&3・Jobsで金儲けをする。 &fhttps://azisabaofficial.playing.wiki/d/%bf%a6%b6%c8%2dJobs'
    - '&3・商店街に店を出す。 &fhttps://azisabaofficial.playing.wiki/d/%be%a6%c5%b9%b3%b9'
    - '&3・他のユーザーにお金を支払う &a/pay ユーザーネーム'
    - '&3・詳しくはお金についてのWikiページを見てね'
    - '&fhttps://azisabaofficial.playing.wiki/d/%a4%aa%b6%e2%a4%ce%b2%d4%a4%ae%ca%fd'
  Rank:
    - ''
    - '&b&lランクについて'
    - '&7-----------------------------'
    - '&3・チュートリアルをクリアするとランク1になります'
    - '&3・ランク1以降はMCMMOの合計レベルとログイン総時間が一定を超えると'
    - '&3  ランクアップできます'
    - '&3・放置していてもログイン総時間にカウントされます'
    - '&3・&a/ar check 現在のランク to 次のランク'
    - '&3  で次のランク昇格の条件が見れます。'
    - '&3  例: &a/ar check rank1 to rank2&7'
    - '&3・ランクが上がるとできることが増え、生活が便利になっていきます'
    - '&3・詳しくはランクについてのWikiページを見てね'
    - '&https://azisabaofficial.playing.wiki/d/rank%a5%b7%a5%b9%a5%c6%a5%e0'

  Dungeon:
    - ''
    - '&b&lダンジョンについて'
    - '&7-----------------------------'
    - '&3・ダンジョンでは特殊なモブと戦えます。'
    - '&3・ダンジョンのドロップは特殊なアイテムのクラフトなどに使用できます。'
    - '&3・初級ダンジョンは鉄の剣一本、中級ダンジョンは鉄防具とダイヤ剣一本'
    - '&3  でそれぞれ攻略できます'
    - '&3・それ以降のダンジョンはだんだん難易度が上がっていきます'
    - '&3・バニラでは入手できない強い武器や装備が手に入ります'
    - '&3・詳しくはダンジョンについてのWikiページを見てね'
    - '&fhttps://azisabaofficial.playing.wiki/d/%a5%c0%a5%f3%a5%b8%a5%e7%a5%f3.%c5%a8'

  Command:
    - ''
    - '&b&lよく使うコマンドについて'
    - '&7-----------------------------'
    - '&3・スポーンに戻る &a/spawn'
    - '&3・エンダーチェストを開ける &a/ec'
    - '&3・クラフティングテーブルを開ける &a/craft'
    - '&3・町にテレポートする &a/town spawn 町の名前'
    - '&3・お金を支払う &a/pay 相手のユーザーネーム'

  Pet:
    - ''
    - '&b&lペットについて'
    - '&7-----------------------------'
    - '&3・ランク4になるとペットが飼えるようになります'
    - '&3・HP2前後のモブをリードで殴るとペットになります'
    - '&3・ペットを入手したら &a/pcst &3でスキルツリーを選びます'
    - '&3・なついたペットを呼ぶには &a/petc'
    - '&3・詳しくはペットについてのWikiページを見てね'
    - '&fhttps://azisabaofficial.playing.wiki/d/MyPet'

  Mcmmo:
    - ''
    - '&b&lMCMMOについて'
    - '&7-----------------------------'
    - '&3・MCMMOはRPGさながらにレベルアップできるスキルがあります'
    - '&3・スキルに応じてレベルアップのやり方が異なります'
    - '&3・MCMMOの合計レベルが一定以上でないとランクアップできないので'
    - '&3  MCMMOのレベルは積極的に上げましょう'
    - '&3・詳しくはMCMMOについてのWikiページを見てね'
    - '&fhttps://azisabaofficial.playing.wiki/d/MCMMO'

  Recipe:
    - ''
    - '&b&l追加レシピについて'
    - '&7-----------------------------'
    - '&3・追加レシピはバニラのレシピと同じようにクラフティングテーブルでクラフトできます'
    - '&3・バニラのアイテムを使用したものとそれ以外のものがあります'
    - '&3・レシピのリストはスポーン右前方のゲートから行けるレシピワールドで確認しましょう'
    - '&3・うまく使いこなせばバニラで入手できるものよりはるかに優れたアイテムが入手できます'
    - '&3・詳しくは追加レシピについてのWikiページを見てね'
    - '&fhttps://azisabaofficial.playing.wiki/d/%a5%a2%a5%a4%a5%c6%a5%e0%a5%ec%a5%b7%a5%d4'

  Enchant:
    - ''
    - '&b&l追加エンチャントについて'
    - '&7-----------------------------'
    - '&3・追加エンチャントは特別なコマンドを使用します &a/ce'
    - '&3・このコマンドを使うと追加エンチャントGUIが開きます'
    - '&3・GUIでエンチャントレベルを消費することにより、バニラでは入手できないエンチャント本を入手できます'
    - '&3・ダンジョンで素材となるようなアイテムはエンチャントしないようにしましょう。'
    - '&3・詳しくは追加エンチャントについてのWikiページを見てね'
    - '&fhttps://azisabaofficial.playing.wiki/d/%c4%c9%b2%c3%a5%a8%a5%f3%a5%c1%a5%e3%a5%f3%a5%c8%2dCrazyEnchantments'

  Vote:
    - ''
    - '&b&l投票について'
    - '&7-----------------------------'
    - '&3・投票をすると豪華な報酬がもらえます'
    - '&3・何より重要なのが、投票によってのみ入手可能な投票チケットです'
    - '&3・投票チケットは手に持つと移動速度が上昇するアイテムなど'
    - '&3・便利な特殊アイテムの入手に使えます'
    - '&3・投票のリンクを得るには &a/vote'

  Basics:
    - ''
    - '&b&lLife鯖の基本について'
    - '&7-----------------------------'
    - '&3・Life鯖にログインしたらまずは町に所属しましょう'
    - '&3・チャットで「町に入れてほしいです」といえば優しい人が入れてくれます'
    - '&3・コマンドなどは&a/help town&3で確認しましょう'
    - '&3・町に入れてもらったら次は資源ワールドに行って資源を集めましょう'
    - '&3・拠点の建築に必要な資源がそろい、町に所属出来たら拠点を建てましょう'
    - '&3・ここまでくればあなたは立派なLife鯖民です'
    - '&3・これ以降は初級ダンジョンに挑む、ランク2を目指す、お金を集める、拠点と町を発展させるなど'
    - '&3・自分がやりたいことをやりましょう'
    - '&3・わからないことがあればWikiを見ましょう &fhttps://azisabaofficial.playing.wiki/d/Life%c0%b8%b3%e8%bb%aa'
    - '&3・それではLife鯖での生活を楽しんでください！'
