#LifeCore plugin configuration file

website-url: https://azisaba.net/

wiki-url: https://azisabaofficial.playing.wiki/

unofficial-wiki-url: https://aziserver.playing.wiki/


Help:
  Menu:
    - ''
    - '&b&lヘルプメニュー'
    - '&7-----------------------------'
    - '&3ガイドブックの入手 &a/guide'
    - '&3公式Wikiリンクの入手 &a/wiki'
    - '&3非公式Wikiリンクの入手 &a/wiki unofficial'
    - '&3ホームページリンクの入手 &a/web'
    - '&3町について &a/help town'
    - '&3金儲けについて &a/help money'
    - '&3ランクについて &a/help rank'
    - '&3ダンジョンについて &a/help dungeon'