#LifeCore plugin configuration file

website-url: https://azisaba.net/

wiki-url: https://azisabaofficial.playing.wiki/

unofficial-wiki-url: https://aziserver.playing.wiki/


Help:
  Menu:
    - ''
    - '&b&lヘルプメニュー'
    - '&7-----------------------------'
    - '&3ガイドブックの入手 &a/guide'
    - '&3公式Wikiリンクの入手 &a/wiki'
    - '&3非公式Wikiリンクの入手 &a/wiki unofficial'
    - '&3ホームページリンクの入手 &a/web'
    - '&3町について &a/help town'
    - '&3金儲けについて &a/help money'
    - '&3ランクについて &a/help rank'
    - '&3ダンジョンについて &a/help dungeon'
  Town:
    - ''
    - '&b&l町について'
    - '&7-----------------------------'
    - '&3町の作成 &a/town new 希望の村の名前'
    - '&3町の銀行への入金。（土地の購入と維持費は町の銀行から引かれます） &a/town deposit 希望の金額'
    - '&3町の拡張。町に隣接しているチャンクで &a/t claim'
    - '&3町にユーザーを招待する &a/town add ユーザーネーム'
    - '&3町への招待を受け取る &a/accept'
    - '&3町への招待を拒否する &a/deny'
    - '&3町のプロットを販売する &a/plot fs 値段（初心者相手には無料で売ってあげましょう）'
    - '&3町のプロットを購入する &a/plot claim'
    - '&3詳しくは町についてのWikiページ'
    - '&f&lhttps://azisabaofficial.playing.wiki/d/Towny%a4%cb%a4%c4%a4%a4%a4%c6'
    - '&3を見てね'