#LifeCore plugin configuration file

website-url: https://azisaba.net/

wiki-url: https://azisabaofficial.playing.wiki/

unofficial-wiki-url: https://aziserver.playing.wiki/


Help:
  Menu:
    - ''
    - '&b&lヘルプメニュー'
    - '&7-----------------------------'
    - '&3ガイドブックの入手 &a/guide'
    - '&3公式Wikiリンクの入手 &a/wiki'
    - '&3非公式Wikiリンクの入手 &a/wiki unofficial'
    - '&3ホームページリンクの入手 &a/web'
    - '&3町について &a/help town'
    - '&3お金について &a/help money'
    - '&3ランクについて &a/help rank'
    - '&3ダンジョンについて &a/help dungeon'
  Town:
    - ''
    - '&b&l町について'
    - '&7-----------------------------'
    - '&3・町の作成 &a/town new 希望の村の名前'
    - '&3・町の銀行への入金。&a /town deposit 希望の金額'
    - '&3土地の購入と維持費は町の銀行から引かれます'
    - '&3・町の拡張。町に隣接しているチャンクで &a/t claim'
    - '&3・町にユーザーを招待する &a/town add ユーザーネーム'
    - '&3・町への招待を受け取る &a/accept'
    - '&3・町への招待を拒否する &a/deny'
    - '&3・町のプロットを販売する &a/plot fs 値段 &3初心者相手には無料で売ってあげましょう'
    - '&3・町のプロットを購入する &a/plot claim'
    - '&3・詳しくは町についてのWikiページ'
    - '&fhttps://azisabaofficial.playing.wiki/d/Towny%a4%cb%a4%c4%a4%a4%a4%c6'
    - '&3を見てね'
  Money:
    - ''
    - '&b&lお金について'
    - '&7-----------------------------'
    - '&3・所持金の確認 &a/money'
    - '&3・運営ショップでものを買う &a/shop &3してから購入したいアイテムをクリックする。'
    - '&3・運営ショップでものを売る &a/sell &3してから開いたチェストに売りたいアイテムを放り込む。'
    - '&3・Jobsで金儲けをする。 &fhttps://azisabaofficial.playing.wiki/d/%bf%a6%b6%c8%2dJobs'
    - '&3・商店街に店を出す。 &fhttps://azisabaofficial.playing.wiki/d/%be%a6%c5%b9%b3%b9'
    - '&3・他のユーザーにお金を支払う &a/pay ユーザーネーム'
    - '&3・詳しくはお金についてのWikiページ'
    - '&fhttps://azisabaofficial.playing.wiki/d/%be%a6%c5%b9%b3%b9'
    - '&3を見てね'
  Rank:
    - ''
    - '&b&lランクについて'
    - '&7-----------------------------'
    - '&3・チュートリアルをクリアするとランク1になります'
    - '&3・ランク1以降はMCMMOの合計レベルとログイン総時間が一定を超えると'
    - '&3  ランクアップできます'
    - '&3・放置していてもログイン総時間にカウントされます'
    - '&3・&a/ar check 現在のランク to 次のランク&3で次のランク昇格の条件が見れます。'
    - '&3  例: &a/ar check rank1 to rank2&7'
    - '&3・ランクが上がるとできることが増え、生活が便利になっていきます'
    - '&3・詳しくはランクについてのWikiページ'
    - '&fhttps://azisabaofficial.playing.wiki/d/Towny%a4%cb%a4%c4%a4%a4%a4%c6'
    - '&3を見てね'
  Dungeon:
    - ''
    - '&b&lダンジョンについて'
    - '&7-----------------------------'
    - '&3・ダンジョンでは特殊なモブと戦えます。'
    - '&3・ダンジョンのドロップは特殊なアイテムのクラフトなどに使用できます。'
    - '&3・初級ダンジョンは鉄の剣一本、中級ダンジョンは鉄防具とダイヤ剣一本でそれぞれ攻略できます'
    - '&3・それ以降のダンジョンはだんだん難易度が上がっていきます'
    - '&3・バニラでは入手できない強い武器や装備が手に入ります'
    - '&3・詳しくはダンジョンについてのWikiページ'
    - '&fhttps://azisabaofficial.playing.wiki/d/%a5%c0%a5%f3%a5%b8%a5%e7%a5%f3%2e%c5%a8'
    - '&3を見てね'