name: LifeCore
version: @version@
main: com.github.mori01231.lifecore.LifeCore
author: Mori01231
description: Core plugin for Life Server in Azi Server Network

commands:
  wiki:
    description: Show wiki URL.
    permission: lifecore.wiki
    usage: Syntax error! Simply type /wiki to show wiki URL.
  website:
    description: Show website URL.
    aliases: [web, webpage, hp, homepage]
    permission: lifecore.website
    usage: Syntax error! Simply type /website to show website URL.
  help:
    description: Show help page.
    aliases: [tutorial]
    permission: lifecore.help
    usage: Syntax error! Simply type /help to show help page.
  guide:
    description: Get guide book.
    permission: lifecore.guide
    usage: Syntax error! Simply type /guide to get guide book.
  tutorial:
    description: Skip to tutorial.
    permission: lifecore.tutorial
    usage: Syntax error! Simply type /tutorial to skip to tutorial.
  pve:
    description: Teleport to dungeon.
    permission: lifecore.pve
    usage: Syntax error! Simply type /pve to teleport to dungeon.
  rank:
    description: Show rank.
    permission: lifecore.rank
    usage: Syntax error! Simply type /rank to show rank.
  sara:
    description: Switch between showing sara and not.
    permission: lifecore.sara
    usage: Syntax error! Simply type /sara to switch between showing sara and not.
  trash:
    description: Open trash.
    aliases: [gomi]
    permission: lifecore.trash
    usage: Syntax error! Simply type /trash to open trash.

permissions:
  lifecore.*:
    description: Gives access to all LifeCore commands
    children:
      lifecore.website: true
      lifecore.wiki: true
      lifecore.help: true
      lifecore.guide: true
      lifecore.tutorial: true
      lifecore.pve: true
      lifecore.rank: true
      lifecore.sara: true
      lifecore.trash: true
  lifecore.wiki:
    description: Allows you to show the wiki URL.
    default: true
  lifecore.website:
    description: Allows you to show the website URL.
    default: true
  lifecore.help:
    description: Allows you to show help.
    default: true
  lifecore.guide:
    description: Allows you to acquire the guidebook.
    default: true
  lifecore.giveguide:
    description: Allows you to give the guidebook.
    default: false
  lifecore.tutorial:
    description: Allows you to skip to tutorial.
    default: false
  lifecore.pve:
    description: Allows you to skip tp to dungeon.
    default: false
  lifecore.rank:
    description: Allows you to show your rank.
    default: false
  lifecore.sara:
    description: Allows you to switch between showing sara and not.
    default: true
  lifecore.trash:
    description: Allows you to open trash.
    default: true