name: LifeCore
version: @version@
main: com.github.mori01231.lifecore.LifeCore
author: Mori01231
description: Core plugin for Life Server in Azi Server Network
depend:
  - AziPluginMessaging
softdepend:
  - Votifier

commands:
  wiki:
    description: Show wiki URL.
    permission: lifecore.wiki
    usage: Syntax error! Simply type /wiki to show wiki URL.
  website:
    description: Show website URL.
    aliases: [web, webpage, hp, homepage]
    permission: lifecore.website
    usage: Syntax error! Simply type /website to show website URL.
  help:
    description: Show help page.
    aliases: [tutorial]
    permission: lifecore.help
    usage: Syntax error! Simply type /help to show help page.
  guide:
    description: Get guide book.
    permission: lifecore.guide
    usage: Syntax error! Simply type /guide to get guide book.
  tutorial:
    description: Skip to tutorial.
    permission: lifecore.tutorial
    usage: Syntax error! Simply type /tutorial to skip to tutorial.
  travel:
    description: Teleport to travel.
    permission: lifecore.travel
    usage: Syntax error! Simply type /travel to teleport to travel.
  pve:
    description: Teleport to dungeon.
    permission: lifecore.pve
    usage: Syntax error! Simply type /pve to teleport to dungeon.
  pve0:
    description: Teleport to dungeon.
    permission: lifecore.pve
    usage: Syntax error! Simply type /pve0 to teleport to dungeon.
  pve1:
    description: Teleport to dungeon.
    permission: lifecore.pve
    usage: Syntax error! Simply type /pve1 to teleport to dungeon.
  pve2:
    description: Teleport to dungeon.
    permission: lifecore.pve
    usage: Syntax error! Simply type /pve2 to teleport to dungeon.
  life:
    description: Teleport to Life server.
    permission: lifecore.life
    usage: Syntax error! Simply type /life to teleport to Life server.
  resource:
    description: Teleport to LifeResource server.
    permission: lifecore.resource
    usage: Syntax error! Simply type /resource to teleport to LifeResource server.
  event:
    description: Teleport to LifeEvent server.
    permission: lifecore.event
    usage: Syntax error! Simply type /event to teleport to LifeEvent server.
  rank:
    description: Show rank.
    permission: lifecore.rank
    usage: Syntax error! Simply type /rank to show rank.
  trash:
    description: Open trash.
    aliases: [gomi]
    permission: lifecore.trash
    usage: Syntax error! Simply type /trash to open trash.
  pack:
    description: Load resource pack.
    permission: lifecore.pack
    usage: Syntax error! Simply type /pack to load resource pack.
  kiai:
    description: Kiai
    permission: lifecore.kiai
    usage: Syntax error! Simply type /kiai to kiai.
  noob:
    description: noob to life server
    usage: Syntax error! Simply type /noob to noob.
  killnonadmin:
    description: Kill non-admin players who has admin sword in their inventory.
    permission: lifecore.killnonadmin
    usage: Syntax error! Simple type /killnonadmin to kill non-admin players who has admin sword in their inventory.
  mmid:
    description: Shows MYTHIC_TYPE of the item.
    permission: lifecore.mmid
    aliases: ["mythictype"]
    usage: /mmid [player]
  debt:
    description: Shows debt of the player.
    permission: lifecore.debt
    usage: /debt [uuid]
  vote:
    description: Shows vote URL.
    permission: lifecore.vote
    usage: Syntax error! Simply type /vote to show vote URL.

permissions:
  lifecore.*:
    description: Gives access to all LifeCore commands
    children:
      lifecore.website: true
      lifecore.wiki: true
      lifecore.help: true
      lifecore.guide: true
      lifecore.tutorial: true
      lifecore.travel: true
      lifecore.pve: true
      lifecore.life: true
      lifecore.resource: true
      lifecore.event: true
      lifecore.rank: true
      lifecore.trash: true
      lifecore.pack: true
      lifecore.kiai: true
      lifecore.noob: false
      lifecore.killnonadmin: true
      lifecore.canuseadminsword: true
      lifecore.mmid: true
      lifecore.debt: true
      lifecore.debt.others: true
      lifecore.vote: true
  lifecore.wiki:
    description: Allows you to show the wiki URL.
    default: true
  lifecore.website:
    description: Allows you to show the website URL.
    default: true
  lifecore.help:
    description: Allows you to show help.
    default: true
  lifecore.guide:
    description: Allows you to acquire the guidebook.
    default: true
  lifecore.giveguide:
    description: Allows you to give the guidebook.
    default: false
  lifecore.tutorial:
    description: Allows you to skip to tutorial.
    default: false
  lifecore.travel:
    description: Allows you to skip tp to dungeon.
    default: false
  lifecore.pve:
    description: Allows you to skip tp to dungeon.
    default: false
  lifecore.life:
    description: Allows you to go to life server.
    default: true
  lifecore.resource:
    description: Allows you to go to liferesource server.
    default: true
  lifecore.event:
    description: Allows you to go to event server.
    default: true
  lifecore.rank:
    description: Allows you to show your rank.
    default: false
  lifecore.trash:
    description: Allows you to open trash.
    default: true
  lifecore.pack:
    description: Allows you to load the resource pack.
    default: true
  lifecore.kiai:
    description: Allows you to kiai.
    default: true
  lifecore.noob:
    description: Allows you to broadcast noob join message
    default: false
  lifecore.killnonadmin:
    description: Allows you to kill non-admin players who has admin sword in their inventory.
    default: false
  lifecore.canuseadminsword:
    description: Allows you to use admin sword.
    default: false
  lifecore.mmid:
    description: Allows you to get mythic type for the item in main hand.
    default: false
  lifecore.debt:
    description: Allows you to get debt of the player.
    default: true
  lifecore.debt.others:
    description: Allows you to get debt of other players.
    default: false
  lifecore.vote:
    description: Allows you to show vote URL.
    default: true
