name: LifeCore
version: @version@
main: com.github.mori01231.lifecore.LifeCore
author: Mori01231
description: Core plugin for Life Server in Azi Server Network

commands:
  switch:
    description: Change between admin mode and user mode.
    usage: Syntax error! Simply type /switch to change modes.
  wiki:
    description: Show wiki URL.
    permission: lifecore.wiki
    usage: Syntax error! Simply type /wiki to show wiki URL.
  website:
    description: Show website URL.
    aliases: [web, webpage, hp, homepage]
    permission: lifecore.website
    usage: Syntax error! Simply type /website to show website URL.

permissions:
  lifecore.*:
    description: Gives access to all LifeCore commands
    children:
      lifecore.switch: true
      lifecore.wiki: true
  lifecore.wiki:
    description: Allows you to show the wiki URL.
    default: true
  lifecore.website:
    description: Allows you to show the website URL.
    default: true
